name: couldai_user_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  photo_manager: ^3.0.0
  video_player: ^2.8.1
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
